services:
  - type: web
    name: crypto-trading-bot
    env: python
    buildCommand: pip install -r dependencies.txt
    startCommand: python start_render.py
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.11.2
      - key: MEXC_API_KEY
        sync: false
      - key: MEXC_API_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bot-db
          property: connectionString

databases:
  - name: bot-db
    databaseName: trading_bot
    ipAllowList: []